source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.5'
pod 'hpple', '~> 0.1'
pod 'MMDrawerController', '~> 0.5.7'
pod 'SWRevealViewController'
pod 'SVProgressHUD'
pod 'MWPhotoBrowser', '~> 1.4.1'
pod '1PasswordExtension', '~> 1.1.2'
